--[CREATE PROCEDURE SAMPLE_PROCEDURE]
CREATE OR REPLACE PROCEDURE APPS.SAMPLE_PROCEDURE
AS

BEGIN
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');fdskjlhgsd
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
	DBMS_OUTPUT.PUT_LINE('This is a sample procedure');
END;
/
--[CREATE TABLE SAMPLE_TABLE]
CREATE TABLE APPS.SAMPLE_TABLE(COLUMN_A NUMBER);

--[ALTER TABLE SAMPLE_TABLE ADD COLUMN_B]
ALTER TABLE APPS.SAMPLE_TABLE ADD(COLUMN_B NUMBER);

--[ALTER TABLE SAMPLE_TABLE ADD COLUMN_C]
ALTER TABLE APPS.SAMPLE_TABLE ADD(COLUMN_C NUMBER);
--[ALTER TABLE SAMPLE_TABLE ADD COLUMN_D]
ALTER TABLE APPS.SAMPLE_TABLE ADD(COLUMN_D NUMBER);
--[ALTER TABLE SAMPLE_TABLE ADD COLUMN_E]
ALTER TABLE APPS.SAMPLE_TABLE ADD(COLUMN_E NUMBER);
--[END]